
name: Deploy Bicep file
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        region: eastus
        template: ./workload/bicep/deploy-baseline.bicep
        parameters: ./workload/bicep/parameters/deploy-baseline-parameters-example.json avdWorkloadSubsId=${{ secrets.AZURE_SUBSCRIPTION }} deploymentPrefix=ARP3 avdVmLocalUserName=${{ secrets.AVDVMLOCALUSERNAME }} avdVmLocalUserPassword=${{ secrets.AVDVMLOCALUSERPASSWORD }} avdIdentityServiceProvider=EntraID existingHubVnetResourceId=${{ secrets.HUBVNETRESOURCEID }} avdEnterpriseAppObjectId=${{ secrets.AVDENTERPRISEAPPOBJECTID }} avdDeployMonitoring=false createAvdVnet=true createAvdFslogixDeployment=true createPrivateDnsZones=false deployAlaWorkspace=false avdSessionHostLocation=eastus avdManagementPlaneLocation=eastus
        failOnStdErr: false
